package include

import (
	// This list is automatically generated by `make imports`
	_ "gitlab.com/msvechla/vaultbeat/module/vault"
	_ "gitlab.com/msvechla/vaultbeat/module/vault/statsd"
	_ "gitlab.com/msvechla/vaultbeat/module/vault/sys_health"
)
